# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  format:check:
    desc: Verify C# formatting without applying changes
    cmds:
      - dotnet format ./Monsters.slnx --verify-no-changes
    silent: false

  format:
    desc: Apply C# formatting rules to the solution
    cmds:
      - dotnet format ./Monsters.slnx
    silent: false
